# Generated by Django 5.1.2 on 2024-10-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otpstore',
        ),
    ]
