# Generated by Django 5.1.2 on 2024-10-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_otpstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
